# ==========================================
# General
# ==========================================
set -g mouse on
set -g history-limit 30000
set -g default-terminal "xterm-256color"

# ==========================================
# Prefix: C-a
# ==========================================
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# ==========================================
# Splits
# ==========================================
unbind %
bind v split-window -v
unbind '"'
bind h split-window -h

# ==========================================
# Copy mode (vi-style + pbcopy)
# ==========================================
setw -g mode-keys vi
set -g set-clipboard off

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# ==========================================
# Plugins (TPM)
# Install plugins: prefix + I
# Update plugins:  prefix + U
# Remove plugins:  prefix + alt + u
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Keep this line at the very bottom
run '~/.config/tmux/plugins/tpm/tpm'
